import {
  amenities,
  business,
  directionsLink,
  galleryItems,
  hiringDetails,
  images,
  testimonials,
} from "../content";
import type {
  AdminBooking,
  AdminData,
  ApartmentUnit,
  Guest,
  HousekeepingTask,
  MaintenanceIssue,
  MessageLead,
  Payment,
  ReportMetric,
  StaffUser,
  WebsiteContent,
} from "./types";

export const TODAY_ISO = "2026-06-13";

export const mockApartments: ApartmentUnit[] = [
  {
    id: "apt-deluxe-01",
    name: "Deluxe Furnished Apartment",
    unitNumber: "A01",
    type: "Deluxe One-Bedroom",
    description: "A polished furnished apartment for business travel, short stays, and quiet long stays in Choma.",
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    beds: 1,
    amenities: ["Wi-Fi", "Air conditioning", "Smart TV", "Kitchen", "Secure parking"],
    pricePerNight: 950,
    pricePerWeek: 6100,
    pricePerMonth: 23500,
    status: "Occupied",
    cleaningStatus: "Inspected",
    maintenanceStatus: "Clear",
    featuredImage: images.livingRoom,
    galleryImages: [images.livingRoom, images.bedroomWide, images.bathroomShower],
    visibleOnWebsite: true,
    featuredOnHomepage: true,
    floor: "Ground floor",
    notes: "Preferred by corporate guests who need quiet workspace.",
    createdAt: "2025-11-12",
    updatedAt: "2026-06-09",
  },
  {
    id: "apt-exec-02",
    name: "Executive Suite",
    unitNumber: "A02",
    type: "Executive Suite",
    description: "Premium bedroom and lounge arrangement for guests who want a more private serviced apartment feel.",
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    beds: 1,
    amenities: ["Wi-Fi", "Air conditioning", "Smart TV", "Kitchen", "Pool access"],
    pricePerNight: 1200,
    pricePerWeek: 7600,
    pricePerMonth: 29000,
    status: "Booked",
    cleaningStatus: "Ready",
    maintenanceStatus: "Clear",
    featuredImage: images.bedroomWide,
    galleryImages: [images.bedroomWide, images.livingRoom, images.bathroomVanity],
    visibleOnWebsite: true,
    featuredOnHomepage: true,
    floor: "Ground floor",
    notes: "Keep stocked with extra towels for weekend bookings.",
    createdAt: "2025-11-12",
    updatedAt: "2026-06-12",
  },
  {
    id: "apt-family-03",
    name: "Family Apartment",
    unitNumber: "B01",
    type: "Family Two-Bedroom",
    description: "A larger furnished apartment for families, visiting teams, and guests staying several nights.",
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    beds: 3,
    amenities: ["Wi-Fi", "Kitchen", "Smart TV", "Secure parking", "Cleaning services"],
    pricePerNight: 1450,
    pricePerWeek: 9200,
    pricePerMonth: 35000,
    status: "Cleaning",
    cleaningStatus: "Cleaning",
    maintenanceStatus: "Clear",
    featuredImage: images.bedroomWarm,
    galleryImages: [images.bedroomWarm, images.kitchen, images.bathroomShower],
    visibleOnWebsite: true,
    featuredOnHomepage: false,
    floor: "Ground floor",
    notes: "Usually needs extra linen after checkout.",
    createdAt: "2025-12-04",
    updatedAt: "2026-06-13",
  },
  {
    id: "apt-standard-04",
    name: "Standard Furnished Apartment",
    unitNumber: "B02",
    type: "Standard One-Bedroom",
    description: "A practical furnished unit for overnight stops, staff travel, and short business trips.",
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    beds: 1,
    amenities: ["Wi-Fi", "Smart TV", "Kitchen", "Secure parking"],
    pricePerNight: 780,
    pricePerWeek: 5000,
    pricePerMonth: 19800,
    status: "Available",
    cleaningStatus: "Ready",
    maintenanceStatus: "Clear",
    featuredImage: images.bedroomAc,
    galleryImages: [images.bedroomAc, images.bathroomVanity, images.exteriorGarden],
    visibleOnWebsite: true,
    featuredOnHomepage: false,
    floor: "Ground floor",
    notes: "Good for same-day WhatsApp inquiries.",
    createdAt: "2025-12-04",
    updatedAt: "2026-06-11",
  },
  {
    id: "apt-premium-05",
    name: "Premium Two-Bedroom Apartment",
    unitNumber: "C01",
    type: "Premium Two-Bedroom",
    description: "A spacious apartment for longer stays, family visits, and guests who need extra privacy.",
    maxGuests: 5,
    bedrooms: 2,
    bathrooms: 2,
    beds: 3,
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Smart TV", "Pool access", "Secure parking"],
    pricePerNight: 1700,
    pricePerWeek: 10800,
    pricePerMonth: 42000,
    status: "Maintenance",
    cleaningStatus: "Maintenance Required",
    maintenanceStatus: "Blocked",
    featuredImage: images.pool,
    galleryImages: [images.pool, images.bedroomWide, images.livingRoom],
    visibleOnWebsite: false,
    featuredOnHomepage: false,
    floor: "Garden side",
    notes: "Blocked until bathroom leak is resolved.",
    createdAt: "2026-01-18",
    updatedAt: "2026-06-13",
  },
  {
    id: "apt-garden-06",
    name: "Garden View Apartment",
    unitNumber: "C02",
    type: "Garden View Studio",
    description: "A calm studio-facing unit close to the landscaped walkway and secure parking area.",
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    beds: 1,
    amenities: ["Wi-Fi", "Air conditioning", "Smart TV", "Secure parking", "Garden view"],
    pricePerNight: 880,
    pricePerWeek: 5600,
    pricePerMonth: 21500,
    status: "Available",
    cleaningStatus: "Inspected",
    maintenanceStatus: "Clear",
    featuredImage: images.exteriorGarden,
    galleryImages: [images.exteriorGarden, images.bedroomWarm, images.bathroomShower],
    visibleOnWebsite: true,
    featuredOnHomepage: false,
    floor: "Garden side",
    notes: "Often requested by repeat guests who prefer a quiet room.",
    createdAt: "2026-01-18",
    updatedAt: "2026-06-10",
  },
];

export const mockGuests: Guest[] = [
  {
    id: "guest-001",
    fullName: "Martha Chileshe",
    phone: "+260 977 214 650",
    email: "martha.chileshe@example.com",
    idType: "NRC",
    idNumber: "123456/10/1",
    nationality: "Zambian",
    address: "Libala, Lusaka",
    city: "Lusaka",
    notes: "Corporate guest. Usually requests a quiet room and receipt by email.",
    preferences: ["Quiet room", "Email receipt", "Late checkout if available"],
    totalBookings: 4,
    totalSpent: 15800,
    outstandingBalance: 0,
    lastStayDate: "2026-05-28",
    repeatGuest: true,
    blacklisted: false,
    createdAt: "2025-12-08",
    updatedAt: "2026-06-10",
  },
  {
    id: "guest-002",
    fullName: "Brian Hachibamba",
    phone: "+260 966 118 432",
    email: "brian.h@example.com",
    idType: "Passport",
    idNumber: "ZN145289",
    nationality: "Zambian",
    address: "Town Centre",
    city: "Choma",
    notes: "Walk-in guest. Prefers mobile money payments.",
    preferences: ["Mobile Money", "Ground floor"],
    totalBookings: 2,
    totalSpent: 5400,
    outstandingBalance: 700,
    lastStayDate: "2026-06-12",
    repeatGuest: true,
    blacklisted: false,
    createdAt: "2026-02-20",
    updatedAt: "2026-06-12",
  },
  {
    id: "guest-003",
    fullName: "Thandiwe Mumba",
    phone: "+260 955 763 109",
    email: "thandiwe.mumba@example.com",
    idType: "NRC",
    idNumber: "778899/11/1",
    nationality: "Zambian",
    address: "Livingstone Road",
    city: "Livingstone",
    notes: "Family stay. Asked about extra bedding for children.",
    preferences: ["Extra towels", "Family apartment"],
    totalBookings: 1,
    totalSpent: 4350,
    outstandingBalance: 0,
    lastStayDate: "2026-06-13",
    repeatGuest: false,
    blacklisted: false,
    createdAt: "2026-06-01",
    updatedAt: "2026-06-13",
  },
  {
    id: "guest-004",
    fullName: "Joseph Mwansa",
    phone: "+260 976 440 221",
    email: "joseph.mwansa@example.com",
    idType: "NRC",
    idNumber: "551122/10/1",
    nationality: "Zambian",
    address: "Kabwe Road",
    city: "Kabwe",
    notes: "Long-stay inquiry from referral.",
    preferences: ["Monthly quote", "Parking close to unit"],
    totalBookings: 1,
    totalSpent: 29000,
    outstandingBalance: 4000,
    lastStayDate: "2026-06-18",
    repeatGuest: false,
    blacklisted: false,
    createdAt: "2026-05-30",
    updatedAt: "2026-06-12",
  },
  {
    id: "guest-005",
    fullName: "Naledi Phiri",
    phone: "+260 977 550 608",
    email: "naledi.phiri@example.com",
    idType: "NRC",
    idNumber: "337711/10/1",
    nationality: "Zambian",
    address: "Makeni",
    city: "Lusaka",
    notes: "Instagram lead converted to weekend stay.",
    preferences: ["Pool access", "Garden view"],
    totalBookings: 1,
    totalSpent: 1760,
    outstandingBalance: 0,
    lastStayDate: "2026-06-15",
    repeatGuest: false,
    blacklisted: false,
    createdAt: "2026-06-09",
    updatedAt: "2026-06-11",
  },
];

export const mockBookings: AdminBooking[] = [
  {
    id: "booking-001",
    bookingCode: "CLA-260613-A01",
    guestId: "guest-001",
    guestName: "Martha Chileshe",
    guestPhone: "+260 977 214 650",
    guestEmail: "martha.chileshe@example.com",
    apartmentId: "apt-deluxe-01",
    apartmentName: "Deluxe Furnished Apartment",
    checkInDate: "2026-06-12",
    checkOutDate: "2026-06-15",
    nights: 3,
    guestsCount: 1,
    adults: 1,
    children: 0,
    source: "WhatsApp",
    status: "Checked In",
    paymentStatus: "Paid",
    totalAmount: 2850,
    amountPaid: 2850,
    balance: 0,
    depositRequired: 950,
    depositPaid: true,
    specialRequests: "Quiet apartment and emailed receipt.",
    internalNotes: "Repeat guest. Keep invoice ready before checkout.",
    createdBy: "Ruth Njobvu",
    createdAt: "2026-06-09",
    updatedAt: "2026-06-12",
    checkedInAt: "2026-06-12T15:35:00",
  },
  {
    id: "booking-002",
    bookingCode: "CLA-260613-A02",
    guestId: "guest-005",
    guestName: "Naledi Phiri",
    guestPhone: "+260 977 550 608",
    guestEmail: "naledi.phiri@example.com",
    apartmentId: "apt-exec-02",
    apartmentName: "Executive Suite",
    checkInDate: "2026-06-13",
    checkOutDate: "2026-06-15",
    nights: 2,
    guestsCount: 2,
    adults: 2,
    children: 0,
    source: "Instagram",
    status: "Confirmed",
    paymentStatus: "Deposit Paid",
    totalAmount: 2400,
    amountPaid: 1200,
    balance: 1200,
    depositRequired: 1200,
    depositPaid: true,
    specialRequests: "Asked for garden side parking if available.",
    internalNotes: "Confirm arrival time on WhatsApp before 13:00.",
    createdBy: "Ruth Njobvu",
    createdAt: "2026-06-11",
    updatedAt: "2026-06-12",
  },
  {
    id: "booking-003",
    bookingCode: "CLA-260613-B01",
    guestId: "guest-003",
    guestName: "Thandiwe Mumba",
    guestPhone: "+260 955 763 109",
    guestEmail: "thandiwe.mumba@example.com",
    apartmentId: "apt-family-03",
    apartmentName: "Family Apartment",
    checkInDate: "2026-06-10",
    checkOutDate: "2026-06-13",
    nights: 3,
    guestsCount: 4,
    adults: 2,
    children: 2,
    source: "Website",
    status: "Checked Out",
    paymentStatus: "Paid",
    totalAmount: 4350,
    amountPaid: 4350,
    balance: 0,
    depositRequired: 1450,
    depositPaid: true,
    specialRequests: "Extra bedding for children.",
    internalNotes: "Checkout cleaning assigned to Grace.",
    createdBy: "Kelvin Banda",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-13",
    checkedInAt: "2026-06-10T14:10:00",
    checkedOutAt: "2026-06-13T10:25:00",
  },
  {
    id: "booking-004",
    bookingCode: "CLA-260614-C02",
    guestId: "guest-004",
    guestName: "Joseph Mwansa",
    guestPhone: "+260 976 440 221",
    guestEmail: "joseph.mwansa@example.com",
    apartmentId: "apt-garden-06",
    apartmentName: "Garden View Apartment",
    checkInDate: "2026-06-14",
    checkOutDate: "2026-06-18",
    nights: 4,
    guestsCount: 1,
    adults: 1,
    children: 0,
    source: "Referral",
    status: "Awaiting Deposit",
    paymentStatus: "Unpaid",
    totalAmount: 3520,
    amountPaid: 0,
    balance: 3520,
    depositRequired: 880,
    depositPaid: false,
    specialRequests: "Monthly rate discussion if first stay goes well.",
    internalNotes: "Follow up before 18:00 today for deposit.",
    createdBy: "Ruth Njobvu",
    createdAt: "2026-06-12",
    updatedAt: "2026-06-12",
  },
  {
    id: "booking-005",
    bookingCode: "CLA-260616-B02",
    guestId: "guest-002",
    guestName: "Brian Hachibamba",
    guestPhone: "+260 966 118 432",
    guestEmail: "brian.h@example.com",
    apartmentId: "apt-standard-04",
    apartmentName: "Standard Furnished Apartment",
    checkInDate: "2026-06-16",
    checkOutDate: "2026-06-18",
    nights: 2,
    guestsCount: 1,
    adults: 1,
    children: 0,
    source: "Walk-in",
    status: "Pending",
    paymentStatus: "Partially Paid",
    totalAmount: 1560,
    amountPaid: 860,
    balance: 700,
    depositRequired: 780,
    depositPaid: true,
    specialRequests: "Late check-in after 19:00.",
    internalNotes: "Balance due at check-in.",
    createdBy: "Kelvin Banda",
    createdAt: "2026-06-12",
    updatedAt: "2026-06-12",
  },
  {
    id: "booking-006",
    bookingCode: "CLA-260620-A01",
    guestId: "guest-001",
    guestName: "Martha Chileshe",
    guestPhone: "+260 977 214 650",
    guestEmail: "martha.chileshe@example.com",
    apartmentId: "apt-deluxe-01",
    apartmentName: "Deluxe Furnished Apartment",
    checkInDate: "2026-06-20",
    checkOutDate: "2026-06-25",
    nights: 5,
    guestsCount: 1,
    adults: 1,
    children: 0,
    source: "Phone",
    status: "Confirmed",
    paymentStatus: "Deposit Paid",
    totalAmount: 4750,
    amountPaid: 950,
    balance: 3800,
    depositRequired: 950,
    depositPaid: true,
    specialRequests: "Needs desk space.",
    internalNotes: "Corporate guest. Prepare pro-forma invoice.",
    createdBy: "Ruth Njobvu",
    createdAt: "2026-06-08",
    updatedAt: "2026-06-12",
  },
];

export const mockPayments: Payment[] = [
  {
    id: "pay-001",
    bookingId: "booking-001",
    bookingCode: "CLA-260613-A01",
    guestId: "guest-001",
    guestName: "Martha Chileshe",
    apartmentName: "Deluxe Furnished Apartment",
    amountDue: 2850,
    amountPaid: 2850,
    balance: 0,
    method: "Bank Transfer",
    status: "Paid",
    receiptNumber: "RCP-2026-0318",
    paymentDate: "2026-06-12",
    recordedBy: "Ruth Njobvu",
    notes: "Receipt emailed.",
  },
  {
    id: "pay-002",
    bookingId: "booking-002",
    bookingCode: "CLA-260613-A02",
    guestId: "guest-005",
    guestName: "Naledi Phiri",
    apartmentName: "Executive Suite",
    amountDue: 2400,
    amountPaid: 1200,
    balance: 1200,
    method: "Mobile Money",
    status: "Deposit Paid",
    receiptNumber: "RCP-2026-0319",
    paymentDate: "2026-06-11",
    recordedBy: "Kelvin Banda",
    notes: "Balance due at arrival.",
  },
  {
    id: "pay-003",
    bookingId: "booking-003",
    bookingCode: "CLA-260613-B01",
    guestId: "guest-003",
    guestName: "Thandiwe Mumba",
    apartmentName: "Family Apartment",
    amountDue: 4350,
    amountPaid: 4350,
    balance: 0,
    method: "Cash",
    status: "Paid",
    receiptNumber: "RCP-2026-0320",
    paymentDate: "2026-06-13",
    recordedBy: "Ruth Njobvu",
    notes: "Paid on checkout.",
  },
  {
    id: "pay-004",
    bookingId: "booking-004",
    bookingCode: "CLA-260614-C02",
    guestId: "guest-004",
    guestName: "Joseph Mwansa",
    apartmentName: "Garden View Apartment",
    amountDue: 3520,
    amountPaid: 0,
    balance: 3520,
    method: "Other",
    status: "Unpaid",
    receiptNumber: "Pending",
    paymentDate: "2026-06-12",
    recordedBy: "Ruth Njobvu",
    notes: "Deposit reminder scheduled.",
  },
  {
    id: "pay-005",
    bookingId: "booking-005",
    bookingCode: "CLA-260616-B02",
    guestId: "guest-002",
    guestName: "Brian Hachibamba",
    apartmentName: "Standard Furnished Apartment",
    amountDue: 1560,
    amountPaid: 860,
    balance: 700,
    method: "Mobile Money",
    status: "Partially Paid",
    receiptNumber: "RCP-2026-0321",
    paymentDate: "2026-06-12",
    recordedBy: "Kelvin Banda",
    notes: "Balance due at check-in.",
  },
];

const turnoverChecklist = [
  { label: "Change linen", done: true },
  { label: "Clean bathroom", done: true },
  { label: "Mop floors", done: false },
  { label: "Restock towels", done: false },
  { label: "Check Wi-Fi/router", done: false },
  { label: "Final inspection", done: false },
];

export const mockHousekeepingTasks: HousekeepingTask[] = [
  {
    id: "hk-001",
    apartmentId: "apt-family-03",
    apartmentName: "Family Apartment",
    taskType: "Checkout Cleaning",
    status: "In Progress",
    priority: "High",
    assignedTo: "Grace Mutale",
    dueDate: "2026-06-13",
    dueTime: "13:00",
    checklist: turnoverChecklist,
    notes: "Family checkout completed at 10:25. Extra linen required.",
    createdAt: "2026-06-13",
  },
  {
    id: "hk-002",
    apartmentId: "apt-exec-02",
    apartmentName: "Executive Suite",
    taskType: "Inspection",
    status: "Ready for Inspection",
    priority: "Medium",
    assignedTo: "Misozi Tembo",
    dueDate: "2026-06-13",
    dueTime: "12:00",
    checklist: [
      { label: "Inspect bathroom", done: true },
      { label: "Check AC/fan", done: true },
      { label: "Restock soap/toiletries", done: true },
      { label: "Final inspection", done: false },
    ],
    notes: "Guest arrives today. Needs front desk inspection.",
    createdAt: "2026-06-13",
  },
  {
    id: "hk-003",
    apartmentId: "apt-standard-04",
    apartmentName: "Standard Furnished Apartment",
    taskType: "Restock Amenities",
    status: "Pending",
    priority: "Low",
    assignedTo: "Grace Mutale",
    dueDate: "2026-06-13",
    dueTime: "16:00",
    checklist: [
      { label: "Restock towels", done: false },
      { label: "Restock soap/toiletries", done: false },
      { label: "Empty bins", done: false },
    ],
    notes: "Prepare for 16 June walk-in booking.",
    createdAt: "2026-06-12",
  },
  {
    id: "hk-004",
    apartmentId: "apt-deluxe-01",
    apartmentName: "Deluxe Furnished Apartment",
    taskType: "Stayover Cleaning",
    status: "Completed",
    priority: "Medium",
    assignedTo: "Misozi Tembo",
    dueDate: "2026-06-13",
    dueTime: "11:00",
    checklist: [
      { label: "Refresh towels", done: true },
      { label: "Empty bins", done: true },
      { label: "Check TV/remote", done: true },
    ],
    notes: "Guest requested no linen change today.",
    createdAt: "2026-06-13",
    completedAt: "2026-06-13T11:15:00",
  },
];

export const mockMaintenanceIssues: MaintenanceIssue[] = [
  {
    id: "mt-001",
    apartmentId: "apt-premium-05",
    apartmentName: "Premium Two-Bedroom Apartment",
    title: "Bathroom leak near vanity",
    description: "Water collecting below vanity after shower use. Unit remains blocked.",
    priority: "Urgent",
    status: "Waiting for Contractor",
    reportedBy: "Grace Mutale",
    assignedTo: "Patrick Mweene",
    reportedAt: "2026-06-12",
    images: [],
    notes: "Plumber expected this afternoon. Keep unit hidden from website.",
  },
  {
    id: "mt-002",
    apartmentId: "apt-deluxe-01",
    apartmentName: "Deluxe Furnished Apartment",
    title: "Wi-Fi router intermittent",
    description: "Guest reported two short drops yesterday evening.",
    priority: "Medium",
    status: "In Progress",
    reportedBy: "Martha Chileshe",
    assignedTo: "Patrick Mweene",
    reportedAt: "2026-06-12",
    images: [],
    notes: "Router restarted. Monitor again before checkout.",
  },
  {
    id: "mt-003",
    apartmentId: "apt-standard-04",
    apartmentName: "Standard Furnished Apartment",
    title: "Door lock needs repair",
    description: "Lock is stiff from outside when using spare key.",
    priority: "High",
    status: "Open",
    reportedBy: "Kelvin Banda",
    assignedTo: "Patrick Mweene",
    reportedAt: "2026-06-13",
    images: [],
    notes: "Fix before 16 June arrival.",
  },
  {
    id: "mt-004",
    apartmentId: "apt-garden-06",
    apartmentName: "Garden View Apartment",
    title: "Light bulb replacement",
    description: "Garden walkway bulb outside C02 is dim.",
    priority: "Low",
    status: "Resolved",
    reportedBy: "Security",
    assignedTo: "Patrick Mweene",
    reportedAt: "2026-06-10",
    resolvedAt: "2026-06-11",
    images: [],
    notes: "Replaced with warm LED bulb.",
  },
];

export const mockMessageLeads: MessageLead[] = [
  {
    id: "lead-001",
    name: "Agnes Nalumango",
    phone: "+260 977 830 410",
    email: "agnes.n@example.com",
    source: "WhatsApp",
    requestedCheckIn: "2026-06-18",
    requestedCheckOut: "2026-06-21",
    requestedApartmentType: "Executive Suite",
    message: "Hello, do you have an executive apartment available for three nights?",
    status: "New",
    assignedTo: "Ruth Njobvu",
    createdAt: "2026-06-13T08:25:00",
    notes: "Asked for rate and secure parking.",
  },
  {
    id: "lead-002",
    name: "Peter Simukonda",
    phone: "+260 966 446 901",
    email: "peter.s@example.com",
    source: "Facebook",
    requestedCheckIn: "2026-06-14",
    requestedCheckOut: "2026-06-17",
    requestedApartmentType: "Standard Furnished Apartment",
    message: "Need a quiet place near town for work.",
    status: "Quoted",
    assignedTo: "Kelvin Banda",
    createdAt: "2026-06-12T17:40:00",
    lastContactedAt: "2026-06-12T18:05:00",
    notes: "Quoted ZMW 780/night.",
  },
  {
    id: "lead-003",
    name: "Luyando Haamukowa",
    phone: "+260 955 221 875",
    email: "",
    source: "Phone",
    requestedCheckIn: "2026-06-20",
    requestedCheckOut: "2026-07-20",
    requestedApartmentType: "Monthly stay",
    message: "Long-stay quote request for one person.",
    status: "Follow Up",
    assignedTo: "Ruth Njobvu",
    createdAt: "2026-06-11T12:30:00",
    lastContactedAt: "2026-06-12T09:10:00",
    notes: "Needs monthly quote and deposit terms.",
  },
  {
    id: "lead-004",
    name: "Mary Banda",
    phone: "+260 977 110 332",
    email: "mary.banda@example.com",
    source: "Website Form",
    requestedCheckIn: "2026-06-16",
    requestedCheckOut: "2026-06-18",
    requestedApartmentType: "Family Apartment",
    message: "Traveling with children, asking about two-bedroom availability.",
    status: "Converted",
    assignedTo: "Kelvin Banda",
    convertedToBookingId: "booking-005",
    createdAt: "2026-06-10T15:15:00",
    lastContactedAt: "2026-06-10T16:00:00",
    notes: "Converted after WhatsApp follow-up.",
  },
];

export const mockStaffUsers: StaffUser[] = [
  {
    id: "staff-001",
    fullName: "Chipo Mwanza",
    email: "owner@chiposluxapartments.com",
    phone: "+260 764 937 372",
    role: "owner_admin",
    department: "Ownership",
    status: "Active",
    avatar: "CM",
    lastActive: "2026-06-13T09:00:00",
    createdAt: "2025-11-01",
  },
  {
    id: "staff-002",
    fullName: "Ruth Njobvu",
    email: "manager@chiposluxapartments.com",
    phone: "+260 977 301 200",
    role: "manager",
    department: "Operations",
    status: "Active",
    avatar: "RN",
    lastActive: "2026-06-13T08:45:00",
    createdAt: "2025-11-18",
  },
  {
    id: "staff-003",
    fullName: "Kelvin Banda",
    email: "frontdesk@chiposluxapartments.com",
    phone: "+260 966 811 224",
    role: "receptionist",
    department: "Front Desk",
    status: "Active",
    avatar: "KB",
    lastActive: "2026-06-13T08:20:00",
    createdAt: "2026-01-05",
  },
  {
    id: "staff-004",
    fullName: "Grace Mutale",
    email: "housekeeping@chiposluxapartments.com",
    phone: "+260 955 430 872",
    role: "housekeeper",
    department: "Housekeeping",
    status: "Active",
    avatar: "GM",
    lastActive: "2026-06-13T07:50:00",
    createdAt: "2026-01-10",
  },
  {
    id: "staff-005",
    fullName: "Patrick Mweene",
    email: "maintenance@chiposluxapartments.com",
    phone: "+260 977 640 992",
    role: "maintenance",
    department: "Maintenance",
    status: "Active",
    avatar: "PM",
    lastActive: "2026-06-12T18:10:00",
    createdAt: "2026-02-01",
  },
  {
    id: "staff-006",
    fullName: "Misozi Tembo",
    email: "nightsecurity@chiposluxapartments.com",
    phone: "+260 966 240 771",
    role: "security",
    department: "Security",
    status: "Off duty",
    avatar: "MT",
    lastActive: "2026-06-13T06:20:00",
    createdAt: "2026-02-15",
  },
];

export const mockWebsiteContent: WebsiteContent = {
  heroTitle: "Luxury Fully Furnished Apartments in Choma",
  heroSubtitle:
    "Comfortable short and long stay apartments with modern amenities, secure parking, Wi-Fi and excellent customer service.",
  ctaText: "Book Now on WhatsApp",
  aboutText:
    "Chipo's Lux Apartments provides furnished apartments in Choma for guests who want a clean, private, and convenient place to stay.",
  amenities: amenities.map((item) => item.title),
  galleryImages: galleryItems.map((item) => item.image),
  contactPhone: business.phoneDisplay,
  whatsappNumber: business.whatsappNumber,
  email: business.email,
  location: `${business.location}. ${business.locationNote}`,
  mapLink: directionsLink,
  faqItems: [
    {
      question: "Do you accept long stays?",
      answer: "Yes. Guests can request weekly or monthly quotes depending on availability.",
    },
    {
      question: "Is secure parking available?",
      answer: "Yes. The property has secure on-site parking for guests.",
    },
    {
      question: "How do guests book?",
      answer: "Most guests book directly through WhatsApp after sharing preferred dates and guest count.",
    },
  ],
  testimonials: testimonials.map((item) => ({ ...item, visible: true })),
  seoTitle: "Chipo's Lux Apartments | Luxury Furnished Apartments in Choma",
  seoDescription:
    "Luxury fully furnished apartments in Choma for short and long stays. Modern amenities, Wi-Fi, secure parking, and easy WhatsApp booking.",
  promotionalBanner: {
    text: hiringDetails.bannerText,
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    active: true,
  },
};

export const mockReportMetrics: ReportMetric[] = [
  { label: "Revenue this month", value: "ZMW 76,920", change: "+12.4%", period: "vs last month", status: "positive" },
  { label: "Occupancy rate", value: "68%", change: "+6%", period: "June to date", status: "positive" },
  { label: "Average length of stay", value: "3.8 nights", change: "+0.4", period: "current month", status: "positive" },
  { label: "Outstanding balances", value: "ZMW 9,220", change: "Needs follow-up", period: "open bookings", status: "warning" },
  { label: "Website and WhatsApp leads", value: "23", change: "+5", period: "last 7 days", status: "positive" },
  { label: "Maintenance open", value: "3", change: "1 urgent", period: "today", status: "warning" },
];

export const mockAdminData: AdminData = {
  apartments: mockApartments,
  bookings: mockBookings,
  guests: mockGuests,
  payments: mockPayments,
  housekeepingTasks: mockHousekeepingTasks,
  maintenanceIssues: mockMaintenanceIssues,
  messageLeads: mockMessageLeads,
  staffUsers: mockStaffUsers,
  websiteContent: mockWebsiteContent,
  reportMetrics: mockReportMetrics,
};
